/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abcbook;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AslamB
 */
public class LoginMenu extends javax.swing.JFrame {

    /**
     * Creates new form LoginMenu
     */
    public LoginMenu() {
        initComponents();

        // My Design Code - Aslam
        setBounds(300, 50, 800, 620);
        setResizable(false);
        this.TxtUsername.requestFocus();

        // Icon
        ImageIcon icon = new ImageIcon(getClass().getResource("icon.png"));
        setIconImage(icon.getImage());

        // Date Time Display
        Runnable helloRunnable = new Runnable() {
            public void run() {
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                Date date = new Date();
                String nowdate = dateFormat.format(date);
                LblDate.setText(nowdate);
            }
        };
        ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
        executor.scheduleAtFixedRate(helloRunnable, 0, 1, TimeUnit.SECONDS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnForget = new javax.swing.JButton();
        BtnLogin = new javax.swing.JButton();
        TxtPassword = new javax.swing.JPasswordField();
        LblDate = new javax.swing.JLabel();
        LblDate1 = new javax.swing.JLabel();
        LabelBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - ABC Book Company Pvt Ltd - Stock Control System");
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(300, 100, 800, 600));
        setName("FrameLoginMenu"); // NOI18N
        getContentPane().setLayout(null);

        PanelLogin.setBackground(new java.awt.Color(0, 194, 214));
        PanelLogin.setForeground(new java.awt.Color(255, 153, 51));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        TxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        BtnForget.setBackground(new java.awt.Color(0, 0, 0));
        BtnForget.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnForget.setText("Forgot");
        BtnForget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnForgetActionPerformed(evt);
            }
        });

        BtnLogin.setBackground(new java.awt.Color(0, 0, 0));
        BtnLogin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnLogin.setText("Login");
        BtnLogin.setToolTipText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        TxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(TxtPassword)))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnForget, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(55, 55, 55)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLogin)
                    .addComponent(BtnForget))
                .addGap(37, 37, 37))
        );

        getContentPane().add(PanelLogin);
        PanelLogin.setBounds(20, 320, 470, 240);

        LblDate.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        LblDate.setForeground(new java.awt.Color(255, 255, 255));
        LblDate.setText("Aslam");
        getContentPane().add(LblDate);
        LblDate.setBounds(540, 410, 190, 40);

        LblDate1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        LblDate1.setForeground(new java.awt.Color(255, 255, 255));
        LblDate1.setText("Welcome");
        getContentPane().add(LblDate1);
        LblDate1.setBounds(540, 380, 190, 40);

        LabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfolder/BG1.jpg"))); // NOI18N
        getContentPane().add(LabelBG);
        LabelBG.setBounds(0, 0, 800, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed

        User_Abc user = new User_Abc();

        user.setUser(this.TxtUsername.getText());
        user.setPassword(this.TxtPassword.getText());

        if (user.isExist()) {

            if (user.isActive()) {

                if (user.canLogin()) {

                    this.dispose();

                    WelcomeMenu k = new WelcomeMenu(user.getUser());
                    k.setVisible(true);

                } else {

                    JOptionPane.showMessageDialog(this, "Your username or password is wrong !", "Wrong", JOptionPane.ERROR_MESSAGE);

                }

            } else {

                JOptionPane.showMessageDialog(this, "Sorry your account has been deactivated !", "Inactive", JOptionPane.WARNING_MESSAGE);

            }

        } else {

            JOptionPane.showMessageDialog(this, "Your are not valid user !", "Wrong", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnForgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnForgetActionPerformed

        User_Abc forgotUser = new User_Abc();

        String fu = JOptionPane.showInputDialog(this, "What's your username ? ", "Forgot password", JOptionPane.QUESTION_MESSAGE);
        if (fu != null) {

            forgotUser.setUser(fu);

            if (forgotUser.isExist()) {

                if (forgotUser.isActive()) {

                    forgotUser.forgotAction();
                    JOptionPane.showMessageDialog(this, "Hi " + forgotUser.getUser().toUpperCase() + " you will be contacted soon by one of Administrator", "Alert", JOptionPane.INFORMATION_MESSAGE);

                } else {

                    JOptionPane.showMessageDialog(this, "Sorry your account has been deactivated !", "Inactive", JOptionPane.WARNING_MESSAGE);

                }

            } else {

                JOptionPane.showMessageDialog(this, "Your are not valid user !", "Wrong", JOptionPane.ERROR_MESSAGE);

            }
        }

    }//GEN-LAST:event_BtnForgetActionPerformed

    private void TxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswordActionPerformed
        this.BtnLogin.doClick();
        this.TxtUsername.requestFocus();
        this.TxtUsername.selectAll();
    }//GEN-LAST:event_TxtPasswordActionPerformed

    private void TxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsernameActionPerformed
        this.TxtPassword.requestFocus();
        this.TxtPassword.selectAll();
    }//GEN-LAST:event_TxtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnForget;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel LabelBG;
    private javax.swing.JLabel LblDate;
    private javax.swing.JLabel LblDate1;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
